### ISSUE TITLE
Arch Linux Gui

### ISSUE THREAD

**Issue by rvv2023** [MathNodes/meile-gui#41]
tried all the suggested ..various errors

kskroyal@archlinux ~]$ pip3 install meile-gui
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try 'pacman -S
    python-xyz', where xyz is the package you are trying to
    install.
    
    If you wish to install a non-Arch-packaged Python package,
    create a virtual environment using 'python -m venv path/to/venv'.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip.
    
    If you wish to install a non-Arch packaged Python application,
    it may be easiest to use 'pipx install xyz', which will manage a
    virtual environment for you. Make sure you have python-pipx
    installed via pacman.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.
[kskroyal@archlinux ~]$

**Comment by MathNodes** [comment]
I've never used Arch before, so I guess it's a little fussy about installing system wide packages. 

Create a virtual environment to install pip packages like so:

```shell
python3 -m venv ~/meile-venv
```

Then active the virtual environment like so:

```
source ~/meile-venv/bin/activate
```

and try the pip install that way. Make sure your python3 version is not greater than 3.10 because the dependency of Kivy (the UI framework) has not been built by that team for python greater than 3.10

**Comment by rvv2023** [comment]
Nice thx ..let u know

**Comment by freQniK** [comment]
https://github.com/MathNodes/meile-gui/releases/download/v1.7.7/meile-gui-1.7.7-1-x86_64.pkg.tar.zst

**Comment by rvv2023** [comment]
Thx I'll look tonight.

**Comment by rvv2023** [comment]
Wouldn't install some files it couldn't get. I'll try again in a week or so.
