### ISSUE TITLE
DNS issue on Subscriptions list

### ISSUE THREAD

**Issue by Vox-draconis** [MathNodes/meile-gui#54]
Windows version, running on Windows 10.
I can see all nodes, and subscribe to them every time, yet when visiting "My subscriptions", NO subscriptions are listed. The 1st time this happened I changed DNS servers and that worked, yet the issue is back, and switching DNS again, multiple times to multiple different DNS servers have yielded no results, I can't see my subscriptions to activate my VPN - please address this issue.

**Comment by MathNodes** [comment]
Try downloading the latest version (1.7.10) and go into settings and switch RPC to `https://rpc.sentinel.co:443`

See if that helps

**Comment by Vox-draconis** [comment]
Thanks for the reply, I followed your instructions and downloaded the newest release. Upon running it nothing worked; "Error loading wallet", no map, nodes or subscriptions. So I cleaned up all remnants of files in the user folder and ran it again.
Imported wallet, and map with nodes were back. No subscriptions showed though, but the node I subscribed to back then was there, so I took another sub on that node.
So now I'm back on my dVPN (great), yet I hardly used any of my past sub, which is nowhere to be found.
I'm sure it's the same wallet I used back then, which I imported now. Would be nice not to lose that previous sub bandwidth though.

**Comment by freQniK** [comment]
I think this relates to the Sentinel Upgrade that happened on August 18th. Part of the upgrade rolled out a new subscription module in which all prior subscriptions before that date were refunded to the wallet. It was a blank slate for the subscription plans and so that may be why you didn't see any of your past subscriptions. Any unused data was unsubscribed and refunded. This is not something with Meile but occurred during the blockchain upgrade.

**Comment by Vox-draconis** [comment]
Thanks for the update, appreciate it.

Would be nice if there was a notification somewhere that could have displayed to not keep paying customers in the dark.

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------
