### ISSUE TITLE
osascript needs admin permissions to run

### ISSUE THREAD

**Issue by 4coffeeihadbreakfast** [MathNodes/meile-gui#96]
Why does connecting to a subscribed node require admin permissions for osascript? (Mac OS X)

**Comment by MathNodes** [comment]
HI. It may seem unconvential to use osascript to handle the network tunnel, however this was our approach for OS X. As with any operating system with a non privileged user, changing networking settings, especially brining up of a tunnel interface requires administration privileges to do so. The osascript that we use simply prompts the user to use their fingeprint or enter their password to grant access to bring up the networking tunnel in order to establish a connection with the desired node. 

In the future and when we can find a solid OS X developer we will begin to use the Apple system APIs to handle these requests. As such for the time being we enable this through osascript.

Closing as there is nothing to be done atm on this.
