### ISSUE TITLE
Bug in routes.sh with v2ray nodes in Linux

### ISSUE THREAD

**Issue by freQniK** [MathNodes/meile-gui#98]
Sometimes when connecting to a v2ray node in Meile, the following error spits out before v2ray goes nuts

```shell
Error: either "to" is duplicate, or "192.168.1.1" is a garbage.
```

it may have to do with this line:

https://github.com/MathNodes/meile-gui/blob/ec2dc231860d5ddb5110a3b6220c8b5cb6e40973/src/bin/routes.sh#L43

This error causes a lot of resources to be consumed as the routes go into a continuous loop and propagating faster and faster. 

Debugging statements should be applied to `routes.sh` to see exactly what line is causing this error.

**Comment by MathNodes** [comment]
I created echo statements for this file on my other PC. I will commit the debug echoes shortly. 

⁣freQniK- Core Developer
MathNodes
www.mathnodes.com​

**Comment by MathNodes** [comment]
This is fixed. However one my one HP machine, for whatever reason it sets the tunnel for the gateway as a duplicate IP and causes v2ray not to function. It's the only box that does this. I've also noticed stranged things on that box. But this was also fixed by stripping the newline character out of the command results.
